// Attack Patterns
#include "AttackPattern_ShootHorizontal.h"
#include "AttackPattern_Explode.h"
#include "AttackPattern_ShootAtPlayer.h"
#include "AttackPattern_VerticleGap.h"
#include "AttackPattern_Wall.h"
#include "AttackPattern_Snake.h"
#include "AttackPattern_ShootandExplode.h"
#include "AttackPattern_SnakeandExplode.h"
#include "AttackPattern_ShootandSnake.h"
#include "AttackPattern_SafeSquares.h"
#include "AttackPattern_HailStorm.h"
